stages:
  - build
  - test


default:
  image: ocaml/opam:debian-12-opam
  before_script:
    # Fonctions pour créer des menus dépliant dans les rapports gitlab
    - header_start () { echo -e "section_start:`date +%s`:${1}\r\e[0K\e[93m${2}\e[0m"; }
    - header_end () { echo -e "section_end:`date +%s`:${1}\r\e[0K"; }


build:
  stage: build

  cache:
    paths:
      - _opam
      - _build

  script:
    # Setup de l'environnement (switch opam et dépendances)
    - if [ -d _opam ]; then echo "Dossier _opam existe, rien à installer"; fi
    - >
      if [ ! -d _opam ]; then
        echo "Pas de dossier _opam, création d'un switch"
        header_start init_env "Création du switch opam"
        opam switch create --yes --deps-only --with-test --with-doc . 5.2.0
        header_end init_env
      fi
    # Build
    - header_start build "Build le projet"
    - eval $(opam env)
    - dune build @all
    - header_end build


test:
  stage: test

  cache:
    paths:
      - _opam
      - _build
    policy: pull

  script:
    - header_start tests "Executer les tests"
    - eval $(opam env)
    - dune test -f
    - header_end tests
